return {
  "mfussenegger/nvim-dap",
  keys = {
    {
      "<leader>b",
      function()
        require("dap").toggle_breakpoint()
      end,
    },
    {
      "<F5>",
      function()
        require("dap").step_into()
      end,
    },
    {
      "<F6>",
      function()
        require("dap").step_over()
      end,
    },
    {
      "<F7>",
      function()
        require("dap").step_out()
      end,
    },
    {
      "<F8>",
      function()
        require("dap").step_back()
      end,
    },
    {
      "<F9>",
      function()
        require("dap").continue()
      end,
    },
    {
      "<F10>",
      function()
        require("dap").terminate()
      end,
    },
  },
}
